### ISSUE TITLE
worse repo i ever seen

### ISSUE THREAD

**Issue by traumatism** [6et/how-to-print-something#1]
if its not a joke, you should delete it

**Comment by 6et** [comment]
Hello Man, This Is No Joke, This Is To Educate  The Beginners (like you because you follow me) So Please Unfollow If You Do Not Like This

**Comment by traumatism** [comment]
wanna educate someone ?


Print(some text)
^              ^

**Comment by 6et** [comment]
```py
>>> Print(some text)
some text
>>>
```
I See Nothing Wrong With This Code-Snippet

**Comment by traumatism** [comment]
```python
┌──(root @ kali)-[/mnt/c/Users/toast]
└─# python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> Print(some text)
  File "<stdin>", line 1
    Print(some text)
               ^
SyntaxError: invalid syntax
>>> Print('hello')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Print' is not defined
>>>
```

**Comment by 6et** [comment]
Kali linux hackerman 😳

**Comment by traumatism** [comment]
yeah

**Comment by 6et** [comment]
> ```python
> ┌──(root @ kali)-[/mnt/c/Users/toast]
> └─# python3
> Python 3.9.2 (default, Feb 28 2021, 17:03:44)
> [GCC 10.2.1 20210110] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> Print(some text)
>   File "<stdin>", line 1
>     Print(some text)
>                ^
> SyntaxError: invalid syntax
> >>> Print('hello')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'Print' is not defined
> >>>
> ```

For Me It Works I Am Using `python 4.10` 👍🏼
